# This is CI Pipeline for Tic Tac Toe project
# It runs on every push to the main branch and on pull requests

name: Tic Tac Toe CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - Kubernetes/*
  pull_request:
    branches: [ main ]

jobs:
    Test:
        name: Run Unit Tests 
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: Set Up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
                with-cache: 'npm'

            - name: Install Project Dependencies
              run: npm ci

            - name: Run Unit Tests
              run: npm test 
    
    Lint:
        name: Perform Static Code Analysis
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: Set Up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
                with-cache: 'npm'

            - name: Install Project Dependencies
              run: npm ci

            - name: Run Linting
              run: npm run lint

    Build:
        name: Build Project
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: Set Up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
                with-cache: 'npm'

            - name: Install Project Dependencies
              run: npm ci

            - name: Build Project
              run: npm run build

            - name: Upload Project Build Artifacts
              uses: actions/upload-artifact@v2
              with:
                name: tic-tac-toe-build 
                path: dist/
                
