# This is CI Pipeline for Tic Tac Toe project
# It runs on every push to the main branch and on pull requests

name: Tic Tac Toe CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - Kubernetes/*
  pull_request:
    branches: [ main ]

jobs:
    test:
        name: Run Unit Tests 
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: Set Up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
                with-cache: 'npm'

            - name: Install Project Dependencies
              run: npm ci

            - name: Run Unit Tests
              run: npm test 